# Generated by Django 5.0.6 on 2024-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('note', models.TextField(null=True)),
                ('appTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('0', 'Waiting'), ('1', 'Done'), ('2', 'Cancel'), ('3', 'Delay')], default='0', max_length=1)),
                ('remark', models.CharField(choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1)),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
