# Generated by Django 5.0.6 on 2024-05-10 09:43

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('request', models.CharField(max_length=128)),
                ('medicalhistory', models.CharField(max_length=128, null=True)),
                ('health', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'Consulting',
            },
        ),
        migrations.CreateModel(
            name='DebtTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.SmallIntegerField()),
                ('customer_id', models.SmallIntegerField(null=True)),
                ('customer_name', models.CharField(max_length=40, null=True)),
                ('inv_fee_note', models.CharField(max_length=128, null=True)),
                ('inv_fee_paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('inv_fee_paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
                ('inv_pay_note', models.CharField(max_length=128, null=True)),
                ('inv_pay_paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('inv_pay_paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
                ('debt_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('debt', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
            ],
            options={
                'db_table': 'DebtTmp',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('service', models.TextField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
            ],
            options={
                'db_table': 'InvoiceFee',
            },
        ),
        migrations.CreateModel(
            name='InvoicePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('time', models.DateTimeField(null=True)),
                ('payby', models.CharField(choices=[('tiền mặt', 'TIỀN MẶT'), ('chuyển khoản', 'CHUYỂN KHOẢN'), ('khác', 'KHÁC')], default='TIỀN MẶT', max_length=12, null=True)),
                ('payed_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('payed', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
                ('paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
                ('discount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('discount', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
                ('other_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('other', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
                ('note', models.TextField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'InvoicePaid',
            },
        ),
        migrations.CreateModel(
            name='InvoiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('time', models.DateTimeField(null=True)),
                ('payby', models.CharField(choices=[('tiền mặt', 'TIỀN MẶT'), ('chuyển khoản', 'CHUYỂN KHOẢN'), ('khác', 'KHÁC')], default='TIỀN MẶT', max_length=12, null=True)),
                ('description', models.TextField()),
                ('paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
                ('payed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'InvoiceProcess',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('date_apply', models.DateField(max_length=10)),
                ('date_end', models.DateField(max_length=10, null=True)),
                ('note', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Treatment',
            },
        ),
        migrations.CreateModel(
            name='TreatmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeO', models.DateTimeField(auto_now_add=True)),
                ('userID', models.SmallIntegerField()),
                ('treat', models.IntegerField()),
                ('quantity', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'TreatmentAsset',
            },
        ),
        migrations.CreateModel(
            name='TreatmentAssetTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.SmallIntegerField()),
                ('asset_name', models.CharField(max_length=80)),
                ('asset_quantity', models.SmallIntegerField()),
                ('asset_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('asset_price', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
                ('asset_sum_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('asset_sum', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
            ],
            options={
                'db_table': 'TreatmentAssetTmp',
            },
        ),
        migrations.CreateModel(
            name='TreatmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('date', models.DateField(max_length=10)),
                ('status', models.TextField(max_length=128)),
                ('tmp_thumb', models.ImageField(blank=True, null=True, upload_to='Treatments')),
            ],
            options={
                'db_table': 'TreatmentProcess',
            },
        ),
        migrations.CreateModel(
            name='TreatmentProcessImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treat', models.IntegerField()),
                ('treat_pro', models.IntegerField()),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='Treatments')),
            ],
            options={
                'db_table': 'TreatmentProcessImages',
            },
        ),
    ]
